### ISSUE TITLE
Computing the relative loss

### ISSUE THREAD

**Issue by zc08** [hosseinshn/GradNorm#2]
Thank you for the code！ 
In GradNormv9.ipynb I think 
`lhat1 = torch.div(l1,l0)
 lhat2 = torch.div(l2,l0)`
where l0 is the averaged loss, is not consistent with the paper. Shouldn't it be the initial costs for the two tasks respectively?

**Comment by hosseinshn** [comment]
Thank you for pointing it out. I added a new notebook (v10) with the correct l0.
