### ISSUE TITLE
Getting gradients of the first layers of each tower and calculate their l2-norm

### ISSUE THREAD

**Issue by Albert-Ma** [hosseinshn/GradNorm#3]
`param = list(model.parameters())`
`G1R = torch.autograd.grad(l1, param[0], retain_graph=True, create_graph=True)`
`G2R = torch.autograd.grad(l2, param[0], retain_graph=True, create_graph=True)`

why does `G1R` and `G2R` use the same param[0] to get gradients of the same layer?
Should they get different gradients of "their own last layer", as "tower1" and "tower2"?

**Comment by zxhuang97** [comment]
Cuz this is the design of the original paper: calculate the gradients of each loss on the last shared layer and balance their impacts.
